// <auto-generated />
using DasGalaxiasAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DasGalaxiasAPI.Migrations
{
    [DbContext(typeof(CursoDbContext))]
    [Migration("20211019132534_AulaCompleto")]
    partial class AulaCompleto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DasGalaxiasAPI.Models.CursoModel", b =>
                {
                    b.Property<int>("AulaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Capa")
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Professor")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("AulaId");

                    b.ToTable("Curso");
                });
#pragma warning restore 612, 618
        }
    }
}
